#spring.application.name=journalApp

#spring.data.mongodb.uri=mongodb+srv://23bq1a4944:KzpqhXKJqtfZRAV8@cluster0.n03eqjq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#spring.main.allow-circular-references=true


spring:
  profiles:
    active: prod
wheather:
  api:
    key: 5edbc1feb2a2247f62e185dab1a809bf
